name: fare-evasion
services:
  web:
    build: .
    ports:
      - "1337:1337"
    command: [ "hypercorn", "app:app", "--bind", "0.0.0.0:1337", "--debug", "--reload" ]
    volumes:
      - db-data:/etc/data
    develop:
      watch:
        - action: sync
          path: .
          target: /code
volumes:
  db-data:
